description: |
  Default image to be used with this orb.
parameters:
  tag:
    type: string
    default: "2020.11"
    description: >
      Pick a specific cimg/base tag:
      https://circleci.com/developer/images/image/cimg/base
docker:
  - image: cimg/base:<<parameters.tag>>
